# App
spring.application.name=livekitdemo
server.port=8080

# H2 In-Memory Datasource
spring.datasource.url=jdbc:h2:mem:livekitdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# H2 Web Console (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# LiveKit
livekit.api.key=devkey
livekit.api.secret=secretqwertyqwertyqwertyqwertysecretqwertyqwertyqwertyqwerty
livekit.url=ws://localhost:7880
server.error.include-message=always
server.error.include-stacktrace=always
